kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: filestorage
networking:
  serviceSubnet: "10.96.0.0/12"
  podSubnet: "10.244.0.0/16"
nodes:
  - role: control-plane
    image: kindest/node:v1.21.10
  - role: worker
    image: kindest/node:v1.21.10
    extraPortMappings:
      - containerPort: 30000
        hostPort: 5000
        listenAddress: "0.0.0.0"
      - containerPort: 30100
        hostPort: 8000
        listenAddress: "0.0.0.0"

