apiVersion: v1
kind: PersistentVolume
metadata:
  name: hamster.volume
  labels:
    target: hamster
    type: hamster_volume
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  hostPath:
    path: /tmp/files

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    target: hamster
    type: hamster_volume
  name: hamster.pvc
spec:
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
