apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry.volume
  labels:
    target: registry
    type: registry_volume
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  hostPath:
    path: /var/lib/registry

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    target: registry
    type: registry_volume
  name: registry.pvc
spec:
  resources:
    requests:
      storage: 8Gi
  storageClassName: local-storage
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
