apiVersion: v1
kind: Service
metadata:
  name: registry-service
spec:
  selector:
    app: registry
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30000
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  labels:
    app: registry
spec:
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      volumes:
        - name: registry-volume
          persistentVolumeClaim:
            claimName: registry.pvc
      containers:
        - name: registry
          volumeMounts:
            - name: registry-volume
              mountPath: /var/lib/registry
          image: registry:2.8.2
          ports:
            - containerPort: 5000

